name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  logger: ^1.1.0  # Move logger here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 

flutter:
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: lib/fonts/Pacifico-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: lib/fonts/SourceSans3-VariableFont_wght.ttf

  assets:
    - lib/Images/Prithvijit.jpg
    - lib/Images/dice1.png
    - lib/Images/dice2.png
    - lib/Images/dice3.png
    - lib/Images/dice4.png
    - lib/Images/dice5.png
    - lib/Images/dice6.png
